name: CI MLflow Project

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 \
            cloudpickle==3.1.2 \
            numpy==2.3.5 \
            pandas==2.3.3 \
            psutil==7.0.0 \
            pyarrow==18.1.0 \
            scikit-learn==1.7.2 \
            scipy==1.16.3 \
            seaborn==0.13.2 \
            matplotlib==3.9.2

      - name: Run MLflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: List mlruns directory
        run: |
          echo "=== Listing mlruns... ==="
          ls -R MLProject/mlruns

      - name: Get MLflow run ID
        id: get_run_id
        run: |
          cd MLProject/mlruns/0
          RUN_ID=$(ls -t | head -n 1)
          echo "Detected RUN_ID=$RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/

      - name: Build Docker Model
        run: |
          echo "Using RUN_ID=$RUN_ID"
          mlflow models build-docker \
            -m "MLProject/mlruns/0/${RUN_ID}/artifacts/model" \
            -n diabetes-mlflow

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag diabetes-mlflow:latest ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-mlflow:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-mlflow:latest
