name: CI MLflow Project

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  mlflow-ci:
    runs-on: ubuntu-latest

    steps:
      # === 1. Checkout repo ===
      - name: Checkout repo
        uses: actions/checkout@v3

      # === 2. Python ===
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # === 3. Check environment ===
      - name: Check Env
        run: |
          python --version
          pip --version

      # === 4. Install dependencies ===
      - name: Install base dependencies
        run: |
          pip install mlflow==2.19.0 \
            cloudpickle==3.1.2 \
            numpy==2.3.5 \
            pandas==2.3.3 \
            psutil==7.0.0 \
            pyarrow==18.1.0 \
            scikit-learn==1.7.2 \
            scipy==1.16.3 \
            seaborn==0.13.2 \
            matplotlib==3.9.2

      # === 5. Jalankan MLflow Project ===
      - name: Run MLflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      # === 6. Debug MLflow outputs ===
      - name: List MLflow outputs
        run: |
          echo "=== List mlruns directory ==="
          ls -R MLProject/mlruns || echo "No mlruns directory!"

      # === 7. Ambil run_id terbaru ===
      - name: Get MLflow run ID
        id: get_run_id
        run: |
          RUN_ID=$(mlflow runs list -l 1 --experiment-id 0 | awk 'NR==2 {print $1}')
          echo "Detected Run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      # === 8. Upload artifact MLflow ke GitHub ===
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns/

      # === 9. Build Docker model ===
      - name: Build Docker Model
        run: |
          cd MLProject
          echo "Using RUN_ID=$RUN_ID"
          mlflow models build-docker \
            -m mlruns/0/$RUN_ID/artifacts/model \
            -n diabetes-mlflow:latest

      # === 10. Login Docker Hub ===
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # === 11. Tag Docker image ===
      - name: Tag Docker Image
        run: |
          docker tag diabetes-mlflow:latest ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-mlflow:latest

      # === 12. Push Docker image ===
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-mlflow:latest
